apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
  namespace: boston
  labels:
    app: ml-app
spec:
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - image: mtszw/ml-app-template:v1
        name: ml-app
        ports:
        - containerPort: 5000
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
